#include "pch.h"
#include "mission.h"

namespace presencemod::mission
{
    // marston2_or_4_outro, marston5x_outro scripts are not supported because they are used for multiple missions
    const MissionDefinition missions[] = {
        // script hash - mission name
        { joaat::generate("winter1"), "Outlaws from the West" },
        { joaat::generate("winter1_outro"), "Outlaws from the West" },
        { joaat::generate("winter2_intro"), "Enter, Pursued by a Memory" },
        { joaat::generate("winter2"), "Enter, Pursued by a Memory" },
        { joaat::generate("winter2_outro"), "Enter, Pursued by a Memory" },
        { joaat::generate("winter4_intro"), "Who the Hell is Leviticus Cornwall?" },
        { joaat::generate("winter4"), "Who the Hell is Leviticus Cornwall?" },
        { joaat::generate("winter4_outro"), "Who the Hell is Leviticus Cornwall?" },
        { joaat::generate("mudtown1_intro"), "Eastward Bound" },
        { joaat::generate("mudtown1"), "Eastward Bound" },
        { joaat::generate("mudtown1_outro"), "Eastward Bound" },
        { joaat::generate("mudtown2_intro"), "Americans at Rest" },
        { joaat::generate("mudtown2"), "Americans at Rest" },
        { joaat::generate("mudtown3_intro"), "Polite Society, Valentine Style" },
        { joaat::generate("mudtown3"), "Polite Society, Valentine Style" },
        { joaat::generate("mudtown3_outro"), "Polite Society, Valentine Style" },
        { joaat::generate("mudtown4_intro"), "The Sheep and the Goats" },
        { joaat::generate("mudtown4"), "The Sheep and the Goats" },
        { joaat::generate("mudtown5_intro"), "Sodom? Back to Gomorrah" },
        { joaat::generate("mudtown5"), "Sodom? Back to Gomorrah" },
        { joaat::generate("mary1_intro"), "We Loved Once and True - III" },
        { joaat::generate("mary1"), "We Loved Once and True - III" },
        { joaat::generate("saloon1_intro"), "A Quiet Time" },
        { joaat::generate("saloon1"), "A Quiet Time" },
        { joaat::generate("saloon1_outro"), "A Quiet Time" },
        { joaat::generate("utopia1_intro"), "Blessed are the Meek?" },
        { joaat::generate("utopia1"), "Blessed are the Meek?" },
        { joaat::generate("utopia2_intro"), "An American Pastoral Scene" },
        { joaat::generate("utopia2"), "An American Pastoral Scene" },
        { joaat::generate("utopia2_outro"), "An American Pastoral Scene" },
        { joaat::generate("sean1_intro"), "The First Shall be Last" },
        { joaat::generate("sean1"), "The First Shall be Last" },
        { joaat::generate("mudtown3b_intro"), "Pouring Forth Oil - IV" },
        { joaat::generate("mudtown3b"), "Pouring Forth Oil - IV" },
        { joaat::generate("bounty1_intro"), "Good, Honest, Snake Oil" },
        { joaat::generate("bounty1"), "Good, Honest, Snake Oil" },
        { joaat::generate("bounty1_outro"), "Good, Honest, Snake Oil" },
        { joaat::generate("reverend1_intro"), "Who is Not without Sin" },
        { joaat::generate("reverend1"), "Who is Not without Sin" },
        { joaat::generate("reverend1_outro"), "Who is Not without Sin" },
        { joaat::generate("hunting1_intro"), "Exit Pursued by a Bruised Ego" },
        { joaat::generate("hunting1"), "Exit Pursued by a Bruised Ego" },
        { joaat::generate("feud1_intro"), "The New South" },
        { joaat::generate("feud1"), "The New South" },
        { joaat::generate("feud1_outro"), "The New South" },
        { joaat::generate("grays1_intro"), "American Distillation" },
        { joaat::generate("grays1"), "American Distillation" },
        { joaat::generate("grays1_outro"), "American Distillation" },
        { joaat::generate("grays2_intro"), "Horse Flesh for Dinner" },
        { joaat::generate("grays2"), "Horse Flesh for Dinner" },
        { joaat::generate("grays2_outro"), "Horse Flesh for Dinner" },
        { joaat::generate("grays3_intro"), "A Short Walk in a Pretty Town" },
        { joaat::generate("grays3"), "A Short Walk in a Pretty Town" },
        { joaat::generate("braithwaites1_intro"), "Advertising, the New American Art - II" },
        { joaat::generate("braithwaites1"), "Advertising, the New American Art - II" },
        { joaat::generate("braithwaites1_outro"), "Advertising, the New American Art - II" },
        { joaat::generate("braithwaites2_intro"), "The Fine Joys of Tobacco" },
        { joaat::generate("braithwaites2"), "The Fine Joys of Tobacco" },
        { joaat::generate("braithwaites2_outro"), "The Fine Joys of Tobacco" },
        { joaat::generate("braithwaites3_intro"), "Blood Feuds, Ancient and Modern" },
        { joaat::generate("braithwaites3"), "Blood Feuds, Ancient and Modern" },
        { joaat::generate("trelawny1_intro"), "Magicians for Sport" },
        { joaat::generate("trelawny1"), "Magicians for Sport" },
        { joaat::generate("mob1_intro"), "The Joys of Civilization" },
        { joaat::generate("mob1"), "The Joys of Civilization" },
        { joaat::generate("mob1_outro"), "The Joys of Civilization" },
        { joaat::generate("mob2_intro"), "Angelo Bronte, a Man of Honor" },
        { joaat::generate("mob2"), "Angelo Bronte, a Man of Honor" },
        { joaat::generate("mob3_intro"), "Urban Pleasures" },
        { joaat::generate("mob3"), "Urban Pleasures" },
        { joaat::generate("mob3_outro"), "Urban Pleasures" },
        { joaat::generate("mob4_intro"), "Country Pursuits" },
        { joaat::generate("mob4"), "Country Pursuits" },
        { joaat::generate("mob4_outro"), "Country Pursuits" },
        { joaat::generate("mob5_intro"), "Revenge is a Dish Best Eaten" },
        { joaat::generate("mob5"), "Revenge is a Dish Best Eaten" },
        { joaat::generate("odriscolls1_intro"), "Old Friends" },
        { joaat::generate("odriscolls1"), "Old Friends" },
        { joaat::generate("odriscolls1_outro"), "Old Friends" },
        { joaat::generate("odriscolls3_intro"), "Blessed are the Peacemakers" },
        { joaat::generate("odriscolls3"), "Blessed are the Peacemakers" },
        { joaat::generate("odriscolls3_outro"), "Blessed are the Peacemakers" },
        { joaat::generate("odriscolls4_intro"), "Horsemen, Apocalypses" },
        { joaat::generate("odriscolls4"), "Horsemen, Apocalypses" },
        { joaat::generate("odriscolls5_intro"), "Goodbye, Dear Friend" },
        { joaat::generate("odriscolls5"), "Goodbye, Dear Friend" },
        { joaat::generate("industry1_intro"), "The Gilded Cage" },
        { joaat::generate("industry1"), "The Gilded Cage" },
        { joaat::generate("industry3_intro"), "A Fine Night of Debauchery" },
        { joaat::generate("industry3"), "A Fine Night of Debauchery" },
        { joaat::generate("industry3_outro"), "A Fine Night of Debauchery" },
        { joaat::generate("saint_denis1_intro"), "Banking, the Old American Art" },
        { joaat::generate("saint_denis1"), "Banking, the Old American Art" },
        { joaat::generate("guama1"), "Lost and Not Quite Found" },
        { joaat::generate("guama2"), "Welcome to the New World" },
        { joaat::generate("guarma3_intro"), "Paradise Mercifully Departed" },
        { joaat::generate("guama3"), "Paradise Mercifully Departed" },
        { joaat::generate("fussar1_intro"), "A Kind and Benevolent Despot" },
        { joaat::generate("fussar1"), "A Kind and Benevolent Despot" },
        { joaat::generate("fussar1_outro"), "A Kind and Benevolent Despot" },
        { joaat::generate("fussar2_intro"), "Savagery Unleashed" },
        { joaat::generate("fussar2"), "Savagery Unleashed" },
        { joaat::generate("fussar2_outro"), "Savagery Unleashed" },
        { joaat::generate("smuggler2_intro"), "Hell Hath No Fury" },
        { joaat::generate("smuggler2"), "Hell Hath No Fury" },
        { joaat::generate("smuggler2_outro"), "Hell Hath No Fury" },
        { joaat::generate("gang1_intro"), "Fleeting Joy" },
        { joaat::generate("gang1"), "Fleeting Joy" },
        { joaat::generate("gang1_outro"), "Fleeting Joy" },
        { joaat::generate("gang2_intro"), "Icarus and Friends" },
        { joaat::generate("gang2"), "Icarus and Friends" },
        { joaat::generate("gang3_intro"), "Visiting Hours" },
        { joaat::generate("gang3"), "Visiting Hours" },
        { joaat::generate("cornwall1_intro"), "An Honest Mistake" },
        { joaat::generate("cornwall1"), "An Honest Mistake" },
        { joaat::generate("cornwall1_outro"), "An Honest Mistake" },
        { joaat::generate("train_robbery1_intro"), "Just a Social Call" },
        { joaat::generate("train_robbery1"), "Just a Social Call" },
        { joaat::generate("train_robbery2_intro"), "The Delights of Van Horn" },
        { joaat::generate("train_robbery2"), "The Delights of Van Horn" },
        { joaat::generate("train_robbery3_intro"), "The Bridge to Nowhere" },
        { joaat::generate("train_robbery3"), "The Bridge to Nowhere" },
        { joaat::generate("train_robbery4_intro"), "Our Best Selves" },
        { joaat::generate("train_robbery4"), "Our Best Selves" },
        { joaat::generate("train_robbery4_outro"), "Our Best Selves" },
        { joaat::generate("native1_intro"), "Archeology for Beginners" },
        { joaat::generate("native1"), "Archeology for Beginners" },
        { joaat::generate("native1_outro"), "Archeology for Beginners" },
        { joaat::generate("native2_intro"), "The Fine Art of Conversation" },
        { joaat::generate("native2"), "The Fine Art of Conversation" },
        { joaat::generate("native2_outro"), "The Fine Art of Conversation" },
        { joaat::generate("native3_intro"), "My Last Boy" },
        { joaat::generate("native3"), "My Last Boy" },
        { joaat::generate("native3_outro"), "My Last Boy" },
        { joaat::generate("native_son1_intro"), "A Rage Unleashed" },
        { joaat::generate("native_son1"), "A Rage Unleashed" },
        { joaat::generate("native_son2_intro"), "Favored Sons" },
        { joaat::generate("native_son2"), "Favored Sons" },
        { joaat::generate("native_son3_intro"), "The King's Son" },
        { joaat::generate("native_son3"), "The King's Son" },
        { joaat::generate("native_son3_outro"), "The King's Son" },
        { joaat::generate("finale1"), "Red Dead Redemption" },
        { joaat::generate("finale2_intro"), "American Venom" },
        { joaat::generate("finale2"), "American Venom" },
        { joaat::generate("marston1_intro"), "The Wheel" },
        { joaat::generate("marston1"), "The Wheel" },
        { joaat::generate("marston2_intro"), "Fatherhood, for Idiots" },
        { joaat::generate("marston2"), "Fatherhood, for Idiots" },
        { joaat::generate("marston4_intro"), "Jim Milton Rides, Again?" },
        { joaat::generate("marston4"), "Jim Milton Rides, Again?" },
        { joaat::generate("marston5_1_intro"), "Simple Pleasures" },
        { joaat::generate("marston5_1"), "Simple Pleasures" },
        { joaat::generate("marston5_2_intro"), "Farming, for Beginners" },
        { joaat::generate("marston5_2"), "Farming, for Beginners" },
        { joaat::generate("marston5_3_intro"), "Fatherhood, for Beginners" },
        { joaat::generate("marston5_3"), "Fatherhood, for Beginners" },
        { joaat::generate("laramie1_intro"), "Old Habits" },
        { joaat::generate("laramie1"), "Old Habits" },
        { joaat::generate("marston6_intro"), "Bare Knuckle Friendships" },
        { joaat::generate("marston6"), "Bare Knuckle Friendships" },
        { joaat::generate("marston7_intro"), "The Tool Box" },
        { joaat::generate("marston7"), "The Tool Box" },
        { joaat::generate("marston8_intro"), "Uncle's Bad Day" },
        { joaat::generate("marston8"), "Uncle's Bad Day" },
        { joaat::generate("marston8_outro"), "Uncle's Bad Day" },
        { joaat::generate("beechers2_2_intro"), "A New Jerusalem" },
        { joaat::generate("beechers2_2"), "A New Jerusalem" },
        { joaat::generate("beechers2_2_outro"), "A New Jerusalem" },
        { joaat::generate("abigail2_1_intro"), "Motherhood" },
        { joaat::generate("abigail2_1"), "Motherhood" },
        { joaat::generate("abigail21_outro"), "Motherhood" },
        { joaat::generate("sadie2_intro"), "Gainful Employment" },
        { joaat::generate("sadie2"), "Gainful Employment" },
        { joaat::generate("sadie3_intro"), "A Quick Favor for an Old Friend" },
        { joaat::generate("sadie3"), "A Quick Favor for an Old Friend" },
        { joaat::generate("sadie4_intro"), "A Really Big Bastard" },
        { joaat::generate("sadie4"), "A Really Big Bastard" },
        { joaat::generate("sadie4_outro"), "A Really Big Bastard" },
        { joaat::generate("sadie5_intro"), "An Honest Day's Labors" },
        { joaat::generate("sadie5"), "An Honest Day's Labors" },
        { joaat::generate("sadie5_outro"), "An Honest Day's Labors" },
        { joaat::generate("susan1_intro"), "No, No and Thrice, No" },
        { joaat::generate("susan1"), "No, No and Thrice, No" },
        { joaat::generate("mary3_intro"), "Fatherhood and Other Dreams - II" },
        { joaat::generate("mary3"), "Fatherhood and Other Dreams - II" },
        { joaat::generate("rcm_abigail11"), "A Fisher of Men" },
        { joaat::generate("rcm_beau_and_penelope10"), "The Course of True Love - I" },
        { joaat::generate("rcm_beau_and_penelope11"), "The Course of True Love - II" },
        { joaat::generate("rcm_beau_and_penelope12"), "The Course of True Love - III" },
        { joaat::generate("rcm_beau_and_penelope20"), "The Course of True Love - IV" },
        { joaat::generate("rcm_beau_and_penelope21"), "The Course of True Love - V" },
        { joaat::generate("rcm_braithwaites01"), "Advertising, the New American Art - I" },
        { joaat::generate("rcm_calderon1"), "Help a Brother Out" },
        { joaat::generate("rcm_calderon2"), "Brothers and Sisters, One and All" },
        { joaat::generate("rcm_calderon21"), "Of Men and Angels - I" },
        { joaat::generate("rcm_calderon22"), "Of Men and Angels - II" },
        { joaat::generate("rcm_coach_robbery1"), "Friends in Very Low Places" },
        { joaat::generate("rcm_doctors_opinion1"), "A Fork in the Road" },
        { joaat::generate("rcm_down1"), "Money Lending and Other Sins - I" },
        { joaat::generate("rcm_down1_2"), "Money Lending and Other Sins - I" },
        { joaat::generate("rcm_down2"), "Money Lending and Other Sins - II" },
        { joaat::generate("rcm_down3"), "Money Lending and Other Sins - III" },
        { joaat::generate("rcm_dusters21"), "Paying a Social Call" },
        { joaat::generate("rcm_dusters61"), "Mrs. Sadie Adler, Widow - I" },
        { joaat::generate("rcm_dusters62"), "Mrs. Sadie Adler, Widow - II" },
        { joaat::generate("rcm_dutch11"), "A Strange Kindness" },
        { joaat::generate("rcm_dutch21"), "The Battle of Shady Belle" },
        { joaat::generate("rcm_dutch31"), "That's Murfree Country" },
        { joaat::generate("rcm_edith_down21"), "Do Not Seek Absolution - I" },
        { joaat::generate("rcm_edith_down22"), "Do Not Seek Absolution - II" },
        { joaat::generate("rcm_exconfed11"), "Preaching Forgiveness as He went" },
        { joaat::generate("rcm_gang01"), "Dear Uncle Tacitus" },
        { joaat::generate("rcm_gang02"), "Dear Uncle Tacitus" },
        { joaat::generate("rcm_homerob00"), "The Spines of America" },
        { joaat::generate("rcm_homerob01"), "Social Calls With Mr. Macguire" },
        { joaat::generate("rcm_mary01"), "We Loved Once and True - I" },
        { joaat::generate("rcm_mary02"), "We Loved Once and True - II" },
        { joaat::generate("rcm_mary31"), "Fatherhood and Other Dreams - I" },
        { joaat::generate("rcm_monroe11"), "Honor, Amongst Thieves" },
        { joaat::generate("rcm_mob01"), "The Joys of Civilization" },
        { joaat::generate("rcm_mob02"), "The Joys of Civilization" },
        { joaat::generate("rcm_mudtown3_1"), "Pouring Forth Oil - I" },
        { joaat::generate("rcm_mudtown3_2"), "Pouring Forth Oil - II" },
        { joaat::generate("rcm_mudtown3_3"), "Pouring Forth Oil - III" },
        { joaat::generate("rcm_native1"), "American Fathers - I" },
        { joaat::generate("rcm_native2"), "American Fathers - II" },
        { joaat::generate("rcm_pearson1"), "The Aftermath of Genesis" },
        { joaat::generate("rcm_sadie11"), "Further Questions of Female Suffrage" },
        { joaat::generate("rcm_strauss11"), "Money Lending and Other Sins - IV" },
        { joaat::generate("rcm_strauss31"), "Money Lending and Other Sins - VI" },
        { joaat::generate("rcm_strauss32"), "Money Lending and Other Sins - VI" },
        { joaat::generate("rcm_strauss33"), "Money Lending and Other Sins - VII" },
        { joaat::generate("rcm_callaway1"), "The Noblest of Men, and a Woman" },
        { joaat::generate("rcm_callaway12"), "The Noblest of Men, and a Woman - II" },
        { joaat::generate("rcm_callaway2"), "The Noblest of Men, and a Woman - III" },
        { joaat::generate("rcm_callaway3"), "The Noblest of Men, and a Woman - IV" },
        { joaat::generate("rcm_chain_gang1"), "The Ties That Bind Us" },
        { joaat::generate("rcm_chain_gang2"), "The Ties That Bind Us - II" },
        { joaat::generate("rcm_chain_gang3"), "The Ties That Bind Us - II" },
        { joaat::generate("rcm_chain_gang4"), "The Ties That Bind Us - III" },
        { joaat::generate("rcm_chain_gang5"), "The Ties That Bind Us - IV" },
        { joaat::generate("rcm_chain_gang6"), "The Ties That Bind Us - IV" },
        { joaat::generate("rcm_chain_gang7"), "The Ties That Bind Us - V" },
        { joaat::generate("rcm_collect_cigarette_cards1"), "Smoking and Other Hobbies" },
        { joaat::generate("rcm_collect_dinosaur_bones11"), "A Test of Faith" },
        { joaat::generate("rcm_collect_dinosaur_bones12"), "A Test of Faith - II" },
        { joaat::generate("rcm_collect_rare_fish1"), "A Fisher of Fish" },
        { joaat::generate("rcm_collect_rare_fish2"), "A Fisher of Fish - II" },
        { joaat::generate("rcm_collect_rock_faces1"), "Geology for Beginners" },
        { joaat::generate("rcm_collect_rock_faces2"), "Geology for Beginners - II" },
        { joaat::generate("rcm_collect_taxidermy1"), "A Better World, A New Friend - I" },
        { joaat::generate("rcm_collect_taxidermy2"), "A Better World, A New Friend - II" },
        { joaat::generate("rcm_collect_exotics1"), "Duchesses and Other Animals" },
        { joaat::generate("rcm_collect_exotics2"), "Duchesses and Other Animals - II" },
        { joaat::generate("rcm_collect_exotics3"), "Duchesses and Other Animals - III" },
        { joaat::generate("rcm_collect_exotics4"), "Duchesses and Other Animals - IV" },
        { joaat::generate("rcm_collect_exotics5"), "Duchesses and Other Animals - V" },
        { joaat::generate("rcm_collect_exotics6"), "Duchesses and Other Animals - VI" },
        { joaat::generate("rcm_crackpot1"), "A Bright Bouncing Boy" },
        { joaat::generate("rcm_crackpot2"), "A Bright Bouncing Boy - II" },
        { joaat::generate("rcm_crackpot3"), "A Bright Bouncing Boy - III" },
        { joaat::generate("rcm_crawley1"), "A Fine Night For It" },
        { joaat::generate("rcm_creole1"), "No Good Deed" },
        { joaat::generate("rcm_for_my_art1"), "The Artist's Way" },
        { joaat::generate("rcm_for_my_art2"), "The Artist's Way - II" },
        { joaat::generate("rcm_for_my_art3"), "The Artist's Way - III" },
        { joaat::generate("rcm_for_my_art4"), "The Artist's Way - IV" },
        { joaat::generate("rcm_fundraiser"), "Fundraiser" },
        { joaat::generate("rcm_gunslinger1_1"), "Emmet Granger" },
        { joaat::generate("rcm_gunslinger1_2"), "Emmet Granger" },
        { joaat::generate("rcm_gunslinger2_1"), "Flaco Hernández" },
        { joaat::generate("rcm_gunslinger3_1"), "Billy Midnight" },
        { joaat::generate("rcm_gunslinger5_1"), "Black Belle" },
        { joaat::generate("rcm_here_kitty_kitty1"), "He's British, of Course" },
        { joaat::generate("rcm_here_kitty_kitty2"), "He's British, of Course - II" },
        { joaat::generate("rcm_here_kitty_kitty3"), "He's British, of Course - III" },
        { joaat::generate("rcm_here_kitty_kitty4"), "He's British, of Course - IV" },
        { joaat::generate("rcm_here_kitty_kitty5"), "He's British, of Course - V" },
        { joaat::generate("rcm_mason1"), "Arcadia for Amateurs" },
        { joaat::generate("rcm_mason2"), "Arcadia for Amateurs - II" },
        { joaat::generate("rcm_mason3"), "Arcadia for Amateurs - III" },
        { joaat::generate("rcm_mason4"), "Arcadia for Amateurs - IV" },
        { joaat::generate("rcm_mason5"), "Arcadia for Amateurs - V" },
        { joaat::generate("rcm_mr_mayor1"), "Idealism and Pragmatism for Beginners - I" },
        { joaat::generate("rcm_mr_mayor2"), "Idealism and Pragmatism for Beginners - II" },
        { joaat::generate("rcm_mr_mayor3"), "Idealism and Pragmatism for Beginners - III" },
        { joaat::generate("rcm_oh_brother1"), "Oh, Brother" },
        { joaat::generate("rcm_oh_brother2"), "Oh, Brother - II" },
        { joaat::generate("rcm_oh_brother3"), "Oh, Brother - III" },
        { joaat::generate("rcm_poisoned_well1"), "The Wisdom of the Elders" },
        { joaat::generate("rcm_poisoned_well2"), "The Wisdom of the Elders - II" },
        { joaat::generate("rcm_poisoned_well3"), "The Wisdom of the Elders - III" },
        { joaat::generate("rcm_poisoned_well4"), "The Wisdom of the Elders - IV" },
        { joaat::generate("rcm_poisoned_well5"), "The Wisdom of the Elders - V" },
        { joaat::generate("rcm_ride_the_lightning1"), "The Mercies of Knowledge" },
        { joaat::generate("rcm_ride_the_lightning2"), "The Mercies of Knowledge - II" },
        { joaat::generate("rcm_ride_the_lightning3"), "The Mercies of Knowledge - III" },
        { joaat::generate("rcm_ride_the_lightning4"), "The Mercies of Knowledge - IV" },
        { joaat::generate("rcm_ride_the_lightning5"), "The Mercies of Knowledge - V" },
        { joaat::generate("rcm_ride_the_lightning6"), "The Mercies of Knowledge - VI" },
        { joaat::generate("rcm_ride_the_lightning7"), "The Mercies of Knowledge - VII" },
        { joaat::generate("rcm_serial_killer1"), "American Dreams" },
        { joaat::generate("rcm_slave_catcher1"), "The Iniquities of History" },
        { joaat::generate("rcm_slave_catcher2"), "The Iniquities of History - II" },
        { joaat::generate("rcm_strauss21"), "Money Lending and Other Sins - V" },
        { joaat::generate("rcm_the_odd_fellows1"), "The Smell of the Grease Paint" },
        { joaat::generate("rcm_the_odd_fellows2"), "The Smell of the Grease Paint - II" },
        { joaat::generate("rcm_treasure_hunter"), "All That Glitters" },
        { joaat::generate("rcm_war_veteran1"), "The Veteran" },
        { joaat::generate("rcm_war_veteran2"), "The Veteran - II" },
        { joaat::generate("rcm_war_veteran3"), "The Veteran - III" },
        { joaat::generate("rcm_war_veteran4"), "The Veteran - IV" },
        { joaat::generate("rcm_bounty_duel1"), "Joshua Brown" },
        { joaat::generate("rcm_bounty_exconfed1"), "Lindsey Wofford" },
        { joaat::generate("rcm_bounty_rancher1"), "Mark Johnson" },
        { joaat::generate("rcm_bh_wife_and_lover"), "Ellie Anne Swan" },
        { joaat::generate("rcm_bh_shack_escape"), "Robbie Laidlaw" },
        { joaat::generate("rcm_bh_sd_saloon"), "Anthony Foreman" },
        { joaat::generate("rcm_bh_skinner_brother"), "Otis Skinner" },
        { joaat::generate("rcm_bh_skinner_search"), "Elias Green" },
        { joaat::generate("rcm_bh_blackwater_hunt"), "Herman Zizendorf" },
        { joaat::generate("rcm_bh_bandito_shack"), "Joaquín Arroyo" },
        { joaat::generate("rcm_bh_bandito_mine"), "Esteban Cortez" },
        { joaat::generate("rcm_abigail22"), "The Best of Women" },
        { joaat::generate("rcm_abigail31"), "A New Future Imagined" },
        { joaat::generate("rcm_beechers11"), "The Landowning Classes" },
        { joaat::generate("rcm_beechers12"), "Home of the Gentry?" },
        { joaat::generate("rcm_beechers21"), "Home Improvement for Beginners" },
        { joaat::generate("rcm_evelyn_miller1"), "The American Inferno, Burnt Out" },
        { joaat::generate("rcm_evelyn_miller2"), "The American Inferno, Burnt Out - II" },
        { joaat::generate("rcm_evelyn_miller3"), "The American Inferno, Burnt Out - III" },
        { joaat::generate("rcm_evelyn_miller4"), "The American Inferno, Burnt Out - IV" },
        { joaat::generate("rcm_evelyn_miller5"), "The American Inferno, Burnt Out - V" },
        { joaat::generate("rcm_jack2"), "Trying Again" },
        { joaat::generate("rcm_marybeth1"), "Mary-Beth" },
        { joaat::generate("rcm_rains_fall1"), "Rains Fall" },
        { joaat::generate("rcm_tilly1"), "Tilly" },
        { joaat::generate("rcm_herbalist_camp"), "To the Ends of the Earth" },
        { joaat::generate("rcm_bh_laramie_sleeping"), "Bart Cavanaugh" },
        { joaat::generate("rcm_bh_camp_return"), "Camille de Millemont" },
    };

    std::string getActiveMissionName()
    {
        for (const auto& mission : missions)
        {
            if (SCRIPTS::_GET_NUMBER_OF_REFERENCES_OF_SCRIPT_WITH_NAME_HASH(mission.scriptHash) > 0)
            {
                return mission.name;
            }
        }

        return "Unknown Mission";
    }
}